module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#161c28",
        "surface-container": "#1a202c",
        "on-tertiary-container": "#5448dc",
        "surface-tint": "#00dbe8",
        "on-error": "#690005",
        background: "#0e131f",
        "inverse-primary": "#00696f",
        "on-surface-variant": "#bac9cb",
        "primary-container": "#38f2ff",
        "surface-variant": "#2f3542",
        "on-tertiary": "#2100a3",
        "surface-container-lowest": "#080e1a",
        outline: "#849495",
        tertiary: "#fbf7ff",
        "on-tertiary-fixed-variant": "#3927c2",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#c4c0ff",
        "on-secondary": "#003258",
        "inverse-on-surface": "#2b303d",
        "on-surface": "#dde2f3",
        "on-primary-container": "#006b72",
        "primary-fixed": "#78f5ff",
        "surface-container-high": "#242a36",
        secondary: "#9ecaff",
        "on-primary-fixed": "#002022",
        "tertiary-container": "#dcd8ff",
        primary: "#e6fdff",
        "on-tertiary-fixed": "#110068",
        "on-primary": "#00363a",
        surface: "#0e131f",
        "tertiary-fixed": "#e3dfff",
        "secondary-fixed-dim": "#9ecaff",
        "inverse-surface": "#dde2f3",
        "outline-variant": "#3b494b",
        "on-primary-fixed-variant": "#004f54",
        error: "#ffb4ab",
        "primary-fixed-dim": "#00dbe8",
        "surface-container-highest": "#2f3542",
        "on-secondary-fixed-variant": "#00497d",
        "secondary-fixed": "#d1e4ff",
        "secondary-container": "#3495ea",
        "on-error-container": "#ffdad6",
        "on-background": "#dde2f3",
        "on-secondary-fixed": "#001d36",
        "surface-bright": "#343946",
        "surface-dim": "#0e131f",
        "on-secondary-container": "#002b4d",
      },
      fontFamily: {
        sans: ["Poppins", "Inter", "sans-serif"],
        "space-grotesk": ['"Space Grotesk"', "sans-serif"],
        jetbrains: ['"JetBrains Mono"', "monospace"],
        "display-hero": ['"Space Grotesk"', "sans-serif"],
        "headline-lg": ['"Space Grotesk"', "sans-serif"],
        "headline-md": ['"Space Grotesk"', "sans-serif"],
        "headline-sm": ['"Space Grotesk"', "sans-serif"],
        "label-caps": ['"JetBrains Mono"', "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      spacing: {
        gutter: "24px",
        "container-padding": "32px",
        "margin-mobile": "20px",
        "margin-desktop": "80px",
        "section-gap": "160px",
        base: "8px",
      },
    },
  },
  plugins: [],
};
